name: glam
channels:
  - anaconda
  - pytorch
  - nvidia
  - nvidia/label/cuda-11.8.0
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - blas=1.0=mkl
  - brotli-python=1.0.9=py311h6a678d5_7
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2024.7.2=h06a4308_0
  - certifi=2024.7.4=py311h06a4308_0
  - cffi=1.16.0=py311h5eee18b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - comm=0.1.2=py311h06a4308_0
  - cryptography=41.0.3=py311hdda0065_0
  - cuda-cccl=11.8.89=0
  - cuda-command-line-tools=11.8.0=0
  - cuda-compiler=11.8.0=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cuobjdump=11.8.86=0
  - cuda-cupti=11.8.87=0
  - cuda-cuxxfilt=11.8.86=0
  - cuda-documentation=11.8.86=0
  - cuda-driver-dev=11.8.89=0
  - cuda-gdb=11.8.86=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=11.8.86=0
  - cuda-nsight-compute=11.8.0=0
  - cuda-nvcc=11.8.89=0
  - cuda-nvdisasm=11.8.86=0
  - cuda-nvml-dev=11.8.86=0
  - cuda-nvprof=11.8.87=0
  - cuda-nvprune=11.8.86=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-nvvp=11.8.87=0
  - cuda-profiler-api=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-sanitizer-api=11.8.86=0
  - cuda-toolkit=11.8.0=0
  - cuda-tools=11.8.0=0
  - cuda-visual-tools=11.8.0=0
  - debugpy=1.6.7=py311h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - faiss-gpu=1.8.0=py3.11_hedc54c9_0_cuda11.4.4
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py311h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - gds-tools=1.4.0.31=0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.28.0=py311h06a4308_0
  - ipython=8.20.0=py311h06a4308_0
  - jedi=0.18.1=py311h06a4308_1
  - jinja2=3.1.2=py311h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jupyter_client=8.6.0=py311h06a4308_0
  - jupyter_core=5.5.0=py311h06a4308_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcufile=1.8.1.2=0
  - libcufile-dev=1.4.0.31=0
  - libcurand=10.3.4.101=0
  - libcurand-dev=10.3.0.86=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libfaiss=1.8.0=h5aaf3ed_0_cuda11.4.4
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py311h5eee18b_0
  - matplotlib-inline=0.1.6=py311h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.8=py311h5eee18b_0
  - mkl_random=1.2.4=py311hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py311h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py311h06a4308_0
  - nsight-compute=2022.3.0.22=0
  - numpy=1.26.0=py311h08b1b3b_0
  - numpy-base=1.26.0=py311hf175353_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.14=h5eee18b_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=10.0.1=py311ha6cbd5a_0
  - pip=23.3=py311h06a4308_0
  - platformdirs=3.10.0=py311h06a4308_0
  - prompt-toolkit=3.0.43=py311h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py311h06a4308_1
  - pyopenssl=23.2.0=py311h06a4308_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.5=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py311h5eee18b_0
  - pyzmq=25.1.0=py311h6a678d5_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py311h06a4308_0
  - setuptools=68.0.0=py311h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.11.1=py311h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=2.1.0=py311_cu118
  - torchvision=0.16.0=py311_cu118
  - tornado=6.3.3=py311h5eee18b_0
  - traitlets=5.7.1=py311h06a4308_0
  - urllib3=1.26.18=py311h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.41.2=py311h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==2.0.0
      - accelerate==0.24.1
      - aenum==3.1.15
      - aiohttp==3.9.0
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - anyio==4.6.2.post1
      - appdirs==1.4.4
      - argostranslate==1.9.6
      - arpeggio==2.0.2
      - attrs==23.1.0
      - autograd==1.7.0
      - autograd-gamma==0.5.0
      - cachetools==5.3.2
      - caliper-reader==0.4.1
      - chardet==3.0.4
      - click==8.1.7
      - contourpy==1.2.0
      - cosine-annealing-warmup==2.0
      - ctranslate2==4.5.0
      - cycler==0.12.1
      - datasets==2.15.0
      - deepspeed==0.14.2
      - diffusers==0.32.2
      - dill==0.3.7
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - einops==0.7.0
      - fairscale==0.4.13
      - flash-attn==2.4.2
      - fonttools==4.45.0
      - formulaic==1.0.2
      - frozenlist==1.4.0
      - fsspec==2023.10.0
      - ftfy==6.3.1
      - gensim==4.3.2
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-auth==2.23.4
      - google-auth-oauthlib==1.1.0
      - googletrans==4.0.0rc1
      - grpcio==1.59.3
      - h11==0.14.0
      - h2==3.2.0
      - hjson==3.1.0
      - hpack==3.0.0
      - hstspreload==2024.2.1
      - httpcore==1.0.7
      - httpx==0.28.0
      - huggingface-hub==0.28.1
      - hydra-core==1.3.2
      - hyperframe==5.2.0
      - idna==2.10
      - imageio==2.34.1
      - imagesize==1.3.0
      - imgaug==0.4.0
      - importlib-metadata==8.6.1
      - interface-meta==1.3.0
      - ipdb==0.13.9
      - jiter==0.8.0
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - lifelines==0.29.0
      - lightly==1.4.26
      - lightly-utils==0.0.2
      - lightning==2.1.2
      - lightning-utilities==0.10.0
      - linkify-it-py==2.0.3
      - llnl-hatchet==2024.1.3
      - markdown==3.5.1
      - markdown-it-py==3.0.0
      - matplotlib==3.8.2
      - mdit-py-plugins==0.4.0
      - mdurl==0.1.2
      - medclip==0.0.3
      - memory-profiler==0.61.0
      - memray==1.11.0
      - mock==5.1.0
      - multidict==6.0.4
      - multiprocess==0.70.15
      - ninja==1.11.1.1
      - nltk==3.8.1
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - open-clip-torch==2.29.0
      - openai==1.56.0
      - opencv-python==4.8.1.78
      - packaging==23.2
      - pandas==2.1.3
      - peft==0.6.2
      - protobuf==4.23.4
      - psutil==5.9.6
      - py-cpuinfo==9.0.0
      - pyarrow==14.0.1
      - pyarrow-hotfix==0.6
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycocotools==2.0.7
      - pydantic==1.10.14
      - pydicom==2.4.3
      - pydot==3.0.3
      - pylibjpeg==2.0.0
      - pynvml==11.5.0
      - pyparsing==3.1.1
      - python-gdcm==3.0.22
      - pytorch-fid==0.3.0
      - pytorch-lightning==2.1.2
      - pytz==2023.3.post1
      - randaugment==1.0.2
      - regex==2023.10.3
      - requests-oauthlib==1.3.1
      - rfc3986==1.5.0
      - rich==13.7.0
      - rsa==4.9
      - sacremoses==0.0.53
      - safetensors==0.4.0
      - scikit-image==0.23.2
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - seaborn==0.13.0
      - sentencepiece==0.2.0
      - sentry-sdk==1.36.0
      - setproctitle==1.3.3
      - shapely==2.0.4
      - smart-open==6.4.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - stanza==1.1.1
      - tenacity==9.0.0
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - terminaltables==3.1.10
      - textaugment==2.0.0
      - textblob==0.17.1
      - textual==0.50.1
      - textx==4.1.0
      - threadpoolctl==3.2.0
      - tifffile==2024.5.3
      - timm==0.9.11
      - tokenizers==0.15.0
      - toml==0.10.2
      - torch==2.1.2+cu118
      - torcheval==0.0.7
      - torchmetrics==1.2.0
      - tqdm==4.66.1
      - transformers==4.35.2
      - triton==2.1.0
      - triton-nightly==3.0.0.post20240716052845
      - typing-extensions==4.12.2
      - tzdata==2023.3
      - uc-micro-py==1.0.3
      - wandb==0.16.0
      - werkzeug==3.0.1
      - wget==3.2
      - wrapt==1.16.0
      - xformers==0.0.23.post1+cu118
      - xxhash==3.4.1
      - yarl==1.9.3
      - zipp==3.21.0
